# Generated by Django 4.2.5 on 2023-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
