# Generated by Django 4.2.5 on 2023-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp2", "0003_alter_client_options_alter_goods_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
